name: Deployment Pipeline to Koyeb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o paycrest

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Deploy to Koyeb
        run: koyeb service redeploy protocol/protocol