name: Pre Merge CI Pipeline 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Go-linter
        uses: Jerome1337/golint-action@v1.0.3

      - name: Set up environment variables
        env:
          ENV_FILE_PATH: '/utils/test/test.env' # Specify the path to your test environment file
        run: |
          echo "ENV_FILE_PATH=$ENV_FILE_PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o paycrest

      - name: Run tests with coverage
        run: go test $(go list ./... | grep -v /ent | grep -v /config | grep -v /database | grep -v /routers)  -coverprofile=coverage.out ./...

      - name: Verify all generated ent files are checked in
        uses: ent/contrib/ci@master