name: Pre Merge CI/CD Pipeline 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1 

      - name: Build
        run: go build -o myapp

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./...

